version: '3.9'
services:
  mongo:
    image: mongo
    container_name: file-storage-mongo
    ports:
      - '27017:27017'
  file_storage:
    build: .
    image: file-storage
    container_name: file-storage-app
    depends_on:
      - mongo
    ports:
      - '8080:8080'
    environment:
      - MONGODB_HOST=file-storage-mongo
      - TELEGRAM_BOT_TOKEN=<token>
      - TELEGRAM_CHAT_ID=<chat_id>
      - TELEGRAM_BOT_ENABLED=true
