version: '3.9'
services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - 27017:27017
  file_storage:
    image: godzilla65536/file_storage
    container_name: file_storage
    depends_on:
      - mongo
    build:
      context: .
    ports:
      - 80:8080
    environment:
      - MONGODB_HOST=mongo
      - MONGODB_PORT=27017
      - MONGODB_DATABASE=file_storage