spring:
  data:
    mongodb:
      host: ${MONGODB_HOST:localhost}
      port: ${MONGODB_PORT:27017}
      database: ${MONGODB_DATABASE:file_storage}

telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN}
    chat-id: -1001549236984
    enabled: ${TELEGRAM_BOT_ENABLED}

springdoc:
  swagger-ui:
    path: /swagger
    disable-swagger-default-url: true
